#ifndef EXCEPTIONS_H_INCLUDED
#define EXCEPTIONS_H_INCLUDED


#define ERR_INIT_AUDIO           100
#define ERR_INIT_AUDIO_FILE      101
#define ERR_INIT_TEXTURE         102
#define ERR_INIT_TEXTURE_FILE    103

#endif // EXCEPTIONS_H_INCLUDED
